const About = () => {
    return (
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam convallis velit at urna faucibus, sit amet elementum leo dictum. Sed sodales fringilla efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean accumsan arcu sit amet dui volutpat, ut accumsan mi ullamcorper. Nullam interdum ante nec mattis suscipit. Maecenas a convallis tellus. Nunc blandit nulla tempor justo tincidunt, ut suscipit dolor tempus. Cras ultricies vestibulum ex, non viverra tortor maximus in. Aliquam et mi varius, tincidunt augue semper, dapibus ligula.

        Nam facilisis purus ac elit vestibulum, eget dictum odio accumsan. Duis tincidunt dignissim leo in feugiat. Donec quis ullamcorper mi, ac dignissim sem. Sed condimentum purus eu dui accumsan, ac ultricies mi pharetra. Curabitur eu vulputate dolor. Sed at ullamcorper neque. Nulla facilisi. Nulla facilisi. Sed volutpat porttitor tempus.
        
        In est tellus, finibus et lobortis id, auctor a tortor. Curabitur porttitor sagittis mollis. Maecenas scelerisque pellentesque sodales. Aliquam sit amet risus in velit malesuada varius. Sed tempor libero a ipsum sodales maximus. Mauris malesuada sagittis justo, quis molestie tellus rhoncus vitae. Donec condimentum pulvinar turpis, sed rutrum tellus rhoncus vel. Duis ornare magna mi, a commodo libero venenatis vitae. Aenean varius, nisi a tempus elementum, risus velit facilisis libero, eu feugiat felis tellus sit amet felis. Nullam ullamcorper euismod libero, et aliquet felis gravida sodales. Fusce convallis lacus id tortor ultrices efficitur. Vestibulum posuere eros eros, et molestie elit euismod non. Nulla auctor suscipit metus. Sed cursus eleifend ipsum.
        
        Nullam dapibus finibus nisi, in fringilla magna pretium vel. Aenean dapibus euismod dui auctor malesuada. Quisque tincidunt felis tortor, sit amet hendrerit orci rhoncus eu. Praesent orci massa, convallis et placerat eget, dignissim id metus. Nullam a facilisis mauris. Sed vehicula molestie pharetra. Nullam placerat pulvinar porttitor. Sed mollis efficitur felis. In malesuada imperdiet mauris quis fermentum.
        
        Maecenas fringilla, felis sit amet volutpat lacinia, nisl nunc vestibulum arcu, nec accumsan justo lorem eget risus. Nam ultrices metus vitae ultrices malesuada. Ut sed euismod elit. In a tincidunt lectus. Vivamus convallis luctus mauris, eget congue felis. Vivamus convallis, sem eget tempor faucibus, nunc nisi sollicitudin dolor, at euismod magna arcu laoreet ipsum. Vestibulum sagittis tincidunt lectus vitae consectetur. Morbi sapien massa, vulputate eget sem sed, pretium dictum neque. Maecenas sit amet lectus auctor est consectetur condimentum. Mauris sagittis vitae libero nec ultricies. Sed laoreet ante sit amet eros elementum laoreet. Donec venenatis cursus malesuada. Sed commodo interdum molestie. Duis lobortis magna magna, ut rutrum massa ultricies vel. Quisque ultricies tellus ac euismod dictum. Praesent lacinia erat tellus, id convallis urna laoreet ut.
        
        Morbi vitae neque felis. Pellentesque convallis mollis aliquet. Maecenas feugiat, urna non rhoncus suscipit, nisi velit facilisis turpis, et mollis nibh neque in nisl. Maecenas egestas ullamcorper metus, a commodo nulla posuere ac. Sed eget odio elementum, egestas mi quis, lobortis mauris. Sed efficitur magna ornare, mattis arcu vitae, consectetur elit. Aenean eget turpis urna. Nunc sed nulla neque. Sed quis tellus et eros convallis hendrerit nec non ante. Duis tincidunt magna nisl, eget gravida purus tincidunt sed. Fusce nec mi felis. Etiam feugiat, quam et gravida tempor, est turpis dictum ante, nec dapibus ipsum nunc vel lectus. Pellentesque consequat libero vitae nisl molestie, at mattis nisi malesuada. Ut porttitor metus neque, ut rutrum nisi tempor quis. Proin fermentum finibus tempor.
        
        Sed viverra tortor quis arcu suscipit consectetur. Cras cursus felis erat, id dictum erat ornare et. Etiam et velit sed nulla hendrerit varius. Quisque rhoncus finibus tellus, et lacinia risus volutpat eu. Suspendisse congue interdum lacus sed efficitur. Vestibulum fermentum ante at tempor congue. Mauris at ex lacinia, accumsan lectus sit amet, iaculis lorem. Nulla dignissim elit lorem, id scelerisque est luctus in.
        
        Vestibulum quis leo ut elit condimentum lacinia sit amet ac felis. Donec cursus, tellus vitae porttitor feugiat, velit odio aliquet justo, ut placerat sapien est at metus. Pellentesque fermentum tristique consectetur. Ut egestas efficitur metus, et pellentesque arcu feugiat et. Etiam turpis purus, ornare lacinia quam id, mattis blandit nibh. Quisque ac dignissim nulla. Fusce porta turpis non maximus porttitor. Duis vitae laoreet felis. Nulla dapibus dolor metus, at rhoncus risus pellentesque quis. Integer vitae congue dolor, nec hendrerit magna. Mauris suscipit felis laoreet ipsum suscipit fringilla.
        
        Suspendisse imperdiet imperdiet orci imperdiet euismod. Curabitur non tortor nisi. Mauris sodales pellentesque neque, a feugiat lorem porttitor id. Maecenas maximus aliquet diam a sagittis. Pellentesque ac velit urna. Duis iaculis blandit nisi, id gravida velit convallis vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus accumsan orci ut tempor tristique. Vestibulum velit sem, mollis eget velit finibus, efficitur rutrum ex. Cras a finibus lectus.
        
        Ut id aliquet lacus. Vestibulum vitae nisi vitae turpis euismod feugiat et sed nibh. Nullam luctus porttitor dolor, sit amet imperdiet mauris commodo eget. Vestibulum facilisis massa varius velit faucibus, ac finibus nulla rhoncus. Fusce eleifend risus eu leo sagittis interdum. Integer lobortis diam quis nisi venenatis semper. Etiam bibendum neque ipsum, non euismod elit scelerisque id. Nam rhoncus enim id sapien elementum commodo. Quisque porta sem nec erat tempor, id efficitur justo condimentum. Aliquam erat volutpat. Morbi lorem felis, molestie eget orci nec, facilisis facilisis ipsum. Aliquam et dolor in ante vestibulum tempor a quis enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec rhoncus vestibulum quam, a elementum ex sagittis vitae.
        
        Fusce diam libero, feugiat et mauris suscipit, pellentesque cursus libero. Vivamus ut eleifend nisl. Nam ultricies cursus tempor. Curabitur consequat elementum libero, ut ultrices purus viverra vitae. Aliquam sed rhoncus eros. Suspendisse potenti. Duis vehicula ipsum nisi, et malesuada leo varius sed. Donec et magna consectetur, consequat libero eu, bibendum enim. Praesent lobortis tincidunt fringilla.
        
        Aliquam eget euismod nisl. Morbi at nisi at tellus gravida ultricies. Donec et dapibus sapien. Morbi auctor, elit nec lobortis ultrices, est est finibus libero, quis bibendum nulla justo ac magna. Maecenas rhoncus at sapien ac lobortis. Integer at ex vitae dui cursus hendrerit fermentum ullamcorper libero. Curabitur luctus fringilla arcu id lobortis. Donec quis sollicitudin ipsum. Vestibulum pellentesque lobortis neque, non feugiat velit tincidunt id. Sed aliquam rhoncus tortor, quis volutpat erat lacinia et. Suspendisse potenti. Nulla vehicula libero augue. Etiam porta, nisl nec viverra auctor, eros ante efficitur sem, eu vulputate est nulla ac est. Morbi non massa orci. In nisi leo, commodo ac aliquam at, sodales vel quam.
        
        Nunc quis lobortis nisl. Nullam dictum sed dolor eu dignissim. Sed congue eros sit amet quam laoreet, eget rutrum erat lacinia. Pellentesque dictum, sem at placerat molestie, nisi erat posuere ante, ac fermentum quam velit et sem. Quisque justo enim, dignissim sed libero nec, scelerisque rutrum ante. Sed sit amet diam at elit porttitor ornare id vitae dui. Aliquam ut dolor neque. Donec at ipsum ut orci bibendum commodo in nec libero. Sed at facilisis nibh. Sed in ultrices turpis. Sed quis dui efficitur purus rutrum varius mattis sed odio. Sed non pulvinar dui. In nec consequat nulla. Aenean ligula magna, bibendum a nibh at, hendrerit fringilla mauris. Aenean neque lacus, tincidunt quis ligula ac, lobortis ultrices eros.
        
        Pellentesque vel nibh et magna porttitor convallis at ut diam. Vestibulum tincidunt vehicula faucibus. In tincidunt, erat egestas dignissim sodales, est nulla hendrerit lacus, ut pharetra justo purus et ipsum. Duis vestibulum at nisl sit amet venenatis. Vestibulum vel lectus sem. Donec venenatis ligula est, ac tempor libero aliquet eget. Nulla dictum ante urna, id porttitor sem egestas vehicula. Integer accumsan leo iaculis, varius nunc in, convallis dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras dapibus libero placerat leo vehicula, a imperdiet elit fringilla. Fusce volutpat odio lorem, sed ultrices magna egestas et. Quisque id est est. Donec porta augue eu felis mattis, in facilisis tellus cursus.
        
        In porttitor ipsum finibus, eleifend lacus sed, hendrerit neque. Sed bibendum augue purus, vel vehicula est eleifend ut. In hac habitasse platea dictumst. Integer gravida, nibh id aliquam vehicula, nunc velit elementum nisl, eget sollicitudin enim libero vel metus. In hac habitasse platea dictumst. Quisque posuere orci risus, in hendrerit nunc scelerisque quis. Cras aliquam rhoncus elit et interdum. Integer accumsan ante sed nulla sollicitudin accumsan. Nam porttitor ex ullamcorper metus vehicula rutrum. Quisque commodo lacus non justo facilisis, nec lacinia erat vulputate. Donec pulvinar at nisi nec posuere. Proin quis ipsum mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam quis risus a leo scelerisque tincidunt. Etiam at nunc at elit gravida consectetur. Maecenas dapibus lorem ac massa viverra, sit amet porta eros tempor.
        
        Nam varius ex sed convallis venenatis. Integer ac magna a nisl convallis venenatis in vitae tortor. Maecenas feugiat tristique risus non semper. Phasellus ac orci eget leo porta egestas. Fusce vitae ipsum nulla. Pellentesque at tristique purus. In quis ligula sollicitudin, congue augue vel, condimentum erat.
        
        Proin at elit nec erat consectetur iaculis. Mauris dignissim purus eu dui efficitur, at sollicitudin elit ultricies. Integer at dui a leo malesuada ultrices. Maecenas dui arcu, interdum eget pellentesque sit amet, vestibulum sit amet metus. In est ipsum, aliquet non dolor ut, interdum pellentesque mauris. Ut lobortis venenatis felis ut egestas. Praesent nunc turpis, commodo sit amet tincidunt id, varius sed felis.
        
        Ut iaculis justo eu justo egestas, in tempus quam condimentum. Pellentesque a placerat mauris. Donec tristique lectus aliquet mauris sollicitudin, in volutpat ipsum sagittis. Sed quam elit, blandit ut dolor eget, pretium viverra nisi. Suspendisse tincidunt orci a orci scelerisque aliquet. Aenean suscipit sed enim congue faucibus. Nullam vitae scelerisque urna, faucibus tristique urna. Etiam eget egestas justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vulputate lectus sed nisl suscipit sodales. Fusce sollicitudin feugiat auctor. Duis vulputate luctus diam.
        
        Vestibulum vitae pulvinar enim. Maecenas ipsum mi, congue non nisl at, fringilla commodo leo. Etiam dapibus erat arcu, eget tristique sapien facilisis non. Proin sapien enim, pharetra in ligula sit amet, eleifend sagittis velit. Etiam ipsum odio, tristique non nibh at, vulputate vulputate magna. Curabitur at varius ligula. Sed quis maximus diam. Maecenas vitae efficitur nulla, sit amet molestie massa. Morbi tortor tellus, semper quis pulvinar a, malesuada dictum dolor.
        
        Nulla ullamcorper et lectus nec tincidunt. Ut ut porttitor arcu. Fusce et porttitor augue. Maecenas sit amet sapien finibus, eleifend ligula sit amet, finibus turpis. Nunc auctor mattis pharetra. Maecenas elementum fermentum gravida. Nulla a porttitor mauris. In quis tincidunt dui, ut tincidunt velit. In hac habitasse platea dictumst. Aenean posuere efficitur sagittis.</div>
    )
}

export default About;